version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - picpay-simplificado

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_nest
    ports:
      - '${API_PORT}:3333'
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
    networks:
      - picpay-simplificado
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  picpay-simplificado:
    driver: bridge
